# Generated by Django 5.1.6 on 2025-02-19 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_paragraph', models.TextField(blank=True, null=True)),
                ('degree_1', models.CharField(blank=True, max_length=255, null=True)),
                ('institution_1', models.CharField(blank=True, max_length=255, null=True)),
                ('year_completed_1', models.IntegerField(blank=True, null=True)),
                ('degree_2', models.CharField(blank=True, max_length=255, null=True)),
                ('institution_2', models.CharField(blank=True, max_length=255, null=True)),
                ('year_completed_2', models.IntegerField(blank=True, null=True)),
                ('degree_3', models.CharField(blank=True, max_length=255, null=True)),
                ('institution_3', models.CharField(blank=True, max_length=255, null=True)),
                ('year_completed_3', models.IntegerField(blank=True, null=True)),
                ('job_title_1', models.CharField(blank=True, max_length=255, null=True)),
                ('company_1', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date_1', models.DateField(blank=True, null=True)),
                ('end_date_1', models.DateField(blank=True, null=True)),
                ('job_description_1', models.TextField(blank=True, null=True)),
                ('job_title_2', models.CharField(blank=True, max_length=255, null=True)),
                ('company_2', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date_2', models.DateField(blank=True, null=True)),
                ('end_date_2', models.DateField(blank=True, null=True)),
                ('job_description_2', models.TextField(blank=True, null=True)),
                ('job_title_3', models.CharField(blank=True, max_length=255, null=True)),
                ('company_3', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date_3', models.DateField(blank=True, null=True)),
                ('end_date_3', models.DateField(blank=True, null=True)),
                ('job_description_3', models.TextField(blank=True, null=True)),
                ('project_title_1', models.CharField(blank=True, max_length=255, null=True)),
                ('project_description_1', models.TextField(blank=True, null=True)),
                ('project_link_1', models.URLField(blank=True, null=True)),
                ('project_title_2', models.CharField(blank=True, max_length=255, null=True)),
                ('project_description_2', models.TextField(blank=True, null=True)),
                ('project_link_2', models.URLField(blank=True, null=True)),
                ('project_title_3', models.CharField(blank=True, max_length=255, null=True)),
                ('project_description_3', models.TextField(blank=True, null=True)),
                ('project_link_3', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
