# Generated by Django 5.1.6 on 2025-03-20 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_first_name_profile_last_name_and_more'),
        ('profiles', '0002_profiles_first_name_profiles_last_name_and_more'),
    ]

    operations = [
    ]
