# Generated by Django 5.1.6 on 2025-03-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_educations_remove_profile_experiences_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experience',
            new_name='Projects',
        ),
    ]
